spring:
  application:
    name: sports-stats-api

  # H2 Database configuration
  datasource:
    url: jdbc:h2:mem:sports_stats_db
    driver-class-name: org.h2.Driver
    username: admin
    password: password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000

  # JPA/Hibernate configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # H2 Console configuration
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  # GraphQL Configuration
  graphql:
    graphiql:
      enabled: true
      path: /graphiql

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Logging configuration
logging:
  level:
    com.applab.sportsstats.sports_stats_api: DEBUG
    org.springframework.web: DEBUG
    root: INFO
